language: sh
addons:
  apt:
    packages:
    - git
    - zsh
script:
- ./bootstrap.sh
- ./install_utility.sh
- ./install_version_manager.sh
- ./tests/test-make-directories.sh
- ./tests/test-make-files.sh
- ./tests/test-xdg-base-directory.sh
- ./tests/test-ignore-dot-symlinks.sh
- ./tests/test-dot-symlinks.sh
- "${HOME}/local/bin/goss --gossfile tests/goss.yaml validate --format documentation"
- zsh -l -c env | egrep -v "^TRAVIS"
