au BufNewFile,BufRead Berksfile setf ruby
au BufNewFile,BufRead Cartfile setf ruby
au BufNewFile,BufRead Dangerfile setf ruby
au BufNewFile,BufRead Fastfile setf ruby
au BufNewFile,BufRead Flavorfile setf ruby
au BufNewFile,BufRead Gemfile{.lock} setf ruby
au BufNewFile,BufRead Guardfile setf ruby
au BufNewFile,BufRead Podfile{.lock} setf ruby
au BufNewFile,BufRead Vagrantfile setf ruby
au BufNewFile,BufRead VimFlavor setf ruby
