name: Acceptance test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash
      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color
        shell: bash
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run installation script
        run: |
          ./bootstrap.sh
          ./install_utility.sh
          ./install_version_manager.sh
      - name: Install checking tool
        run: |
          sudo apt-get update && sudo apt-get install zsh
          curl -fsSL https://goss.rocks/install | GOSS_VER=v0.4.3 GOSS_DST="${HOME}/local/bin" sh
      - name: Run acceptance test and print environment variables
        run: |
          "${HOME}/local/bin/goss" --version
          "${HOME}/local/bin/goss" --gossfile tests/goss.yaml validate --format documentation
          printf "\nPrint Environment variables:\n" && zsh -l -c env
          printf "\nPrint PATHs:\n" && echo "$PATH" | tr ':' '\n'
